name: data-mongo

on:
  push:
    paths:
      - "data-mongo/**"
    branches:
      - master
  pull_request:
    paths:
      - "data-mongo/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -q clean package --file data-mongo/pom.xml
        
      - name: Start up Mongo in Docker
        run: |
          docker compose up -d mongodb
          sleep 5
          docker ps -a 
          
      - name: Unit Tests
        run: mvn -B -q clean test --file data-mongo/pom.xml -Put


      - name: Integration Tests
        run: mvn -B -q clean verify --file data-mongo/pom.xml -Pit-jetty
